dist: xenial
language: python
python:
- 3.7
install: pip install tox
script: tox
deploy:
  notifications:
    email:
      on_success: always
  provider: pypi
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: Tomekske
  password:
    secure: gSAU7yGnrkEmhuG4O1WI2g34Wu3SM9S9HPXleTu2vq7koDwuIP16MaQ/1VEgQilIMfMnh19ASoV3MlW1kCguqF4EDfYCLbkS4S6L02XPIUaXmIdeGy0aajJ7H3OU17HmHHCxjaglcJbHzyntgYmHPBGN+lJgvJBjWnkhB5ny/uaTDxmqFIXsbbtl6mfMma8Acbq7udJ7ewjo+AiAVdH/SMLCJ/GSIA7JOTSReTw49C8w/HS50fj9gBzVYF52ewa9lgKjxkve7WLzB2rNhL5jDZ7Fwhlk9Rvl6mPoz8bWuyQGsiz21TXrYSC3MFz1FAaaQqYTbf2VIbZljy/HI+wLiZlM6dTkXAR36evLcgIMkQhK6rcbBgH5hG3PVA8AKXTLjB9YLDwBgM64muxMUsr3RkP15XrOSZcEFtS++q+f47VyQhjojf7cDsFzD71b89DbQQYTAMhgy90dpxVFrexjRmA+xOVXqFaCPmpysZsi1gZGX18vQla1/TEpbvR7WZS20XR5jG3oj1FXCNBRL0QvT1VbzJh/fD5GXK+ikBBs1MAQeMTrGpd6Cy4ofTkZvRxCN6IICdOSh3NF7Q3XLDNNZkE8TsDmhJ09UNWePZwMwNQo9dpPVvhBREA7XcV7L0germJqKBq2jK338m9kNJrp3db1zd6Uq8LvLZ4+28BQK88=
  on:
    tags: false
    branch: master
    repo: Tomekske/generalutils
